def powerset(nums: list[int]) -> list[list[int]]:
    """ A powerset is generated by mapping the digits of the binary
    numbers from 0 to 1 << len(nums) onto each element in nums.
    We assume the input contains no duplicates.
    Each binary number corresponds to an element (a set of numbers)
    in the powerset. Each digit in that number that is 1 is the index
    for an included element of nums.
    So for example, if nums is [1,2] then we use the digits of the
    binary numbers 00, 01, 10, 11 as indices, corresponding to the sets
    [], [2], [1], [1,2], which together form the power set of nums.
    """
    n = len(nums)
    powset: list[list[int]] = []
    for i in range(1 << n):
        powset.append([nums[j] for j in range(n) if (i >> (n - 1 - j) & 1)])
    return powset


# For testing
from utils import check


def recursive_powset(n: int) -> list[list[int]]:
    if n == 0:
        return [[]]
    previous = recursive_powset(n-1)
    return previous + [subset + [n-1] for subset in previous]


def normalize(powset: list[list[int]]) -> list[list[int]]:
    return sorted([sorted(subset) for subset in powset])


def main() -> None:
    for i in range(8):
        result = normalize(powerset(list(range(i))))
        expected = normalize(recursive_powset(i))
        check(result == expected,
              f"For {i}, expected \n\t{expected}, \ngot \n\t{result}")


if __name__ == "__main__":
    main()
