def powerset(nums: list[int]) -> list[list[int]]:
    """ A powerset is generated by mapping the digits of the binary 
    numbers from 0 to 1 << len(nums) onto each element in nums.
    We assume the input contains no duplicates.
    Each binary number corresponds to an element (a set of numbers) 
    in the powerset. Each digit in that number that is 1 is the index 
    for an included element of nums. 
    So for example, if nums is [1,2] then we use the digits of the 
    binary numbers 00, 01, 10, 11 as indices, corresponding to the sets 
    [], [2], [1], [1,2], which together form the power set of nums.
    """
    n = len(nums)
    powset: list[list[int]] = []
    for i in range(1 << n):
        powset.append([nums[j] for j in range(n) if (i >> (n - 1 - j) & 1)])
    return powset


def main():
    cases = [
        [],
        [1,2],
        [1,2,3],
        [1,2,3,4],
        [1,2,3,4,5],
    ]
    for case in cases:
        print(f"Powset of {case} is: {powerset(case)}")


if __name__ == "__main__":
    main()
