def powerset(nums: list[int]) -> list[list[int]]:
    """ A powerset is generated by mapping the digits of the binary numbers 
    from 0 to 1 << len(nums) onto each element in nums.
    """
    n = len(nums)
    powset: list[list[int]] = []
    for i in range(1 << n):
        powset.append([nums[j] for j in range(n) if (i >> (n - 1 - j) & 1)])
    return powset


def main():
    cases = [
        [],
        [1,2],
        [1,2,3],
        [1,2,3,4],
        [1,2,3,4,5],
    ]
    for case in cases:
        print(f"Powset of {case} is: {powerset(case)}")


if __name__ == "__main__":
    main()
